#!/usr/bin/python3 
import time, os, math
hrs=int(time.strftime("%H"))
mnt=int(time.strftime("%M"))
sec=int(time.strftime("%S"))
dom=int(time.strftime("%d"))
dow=int(time.strftime("%w"))
now=int(time.strftime("%U"))
mon=int(time.strftime("%m"))
doy=int(time.strftime("%j"))
noy=int(time.strftime("%Y"))
dim=int(hrs * 60 + mnt)
dis=int(dim * 60 + sec)
rev=int(dis / 240)
diss=int(dis / 2)
dism=int(diss / 60)
dish=int(dism / 60)
sm=int(dism - dish * 60)
ss=int(diss - dism * 60)


print("Official Time Format :", hrs,":",mnt,":",sec)
print("Sumerian Time Format :", dish,":",sm,":",ss)
print("Planet Revolution    :", rev,"º")
print("Position on orbit    :", doy,"º")
